In [43]:
import pandas as pd
import numpy as np

In [44]:
data = pd.read_pickle('data_clean.pkl')
data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France,10.20
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France,12.60
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France,14.85

In [45]:
data = data[data['StockCode'] != 'POST']
data = data[data['StockCode'] != 'DOT']
data = data[data['StockCode'] != 'M']
data = data[data['StockCode'] != 'BANK CHARGES']
data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France,10.20
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France,12.60
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France,14.85

In [46]:
ABC = data.groupby('StockCode').agg(
    Revenue_stock = ('Revenue', 'sum')
)
ABC = ABC.sort_values(by='Revenue_stock', ascending= False)
ABC

           Revenue_stock
StockCode
23843         168469.600
22423         142264.750
85123A        100547.450
85099B         85040.540
23166          81416.730
...                  ...
90084              0.850
90104              0.850
21268              0.840
84227              0.420
PADS               0.003

[3661 rows x 1 columns]

In [47]:
ABC['Piece'] = ABC['Revenue_stock']/ABC['Revenue_stock'].sum()
ABC['Cum_share'] = ABC['Piece'].cumsum()
ABC

           Revenue_stock         Piece  Cum_share
StockCode
23843         168469.600  1.926707e-02   0.019267
22423         142264.750  1.627015e-02   0.035537
85123A        100547.450  1.149914e-02   0.047036
85099B         85040.540  9.725684e-03   0.056762
23166          81416.730  9.311246e-03   0.066073
...                  ...           ...        ...
90084              0.850  9.721048e-08   1.000000
90104              0.850  9.721048e-08   1.000000
21268              0.840  9.606682e-08   1.000000
84227              0.420  4.803341e-08   1.000000
PADS               0.003  3.430958e-10   1.000000

[3661 rows x 3 columns]

In [48]:
def abc_analys(abc_class):
    if abc_class <=0.8:
        return 'A'
    elif abc_class >0.8 and abc_class <=0.95:
        return 'B'
    else:
        return 'C'
ABC['ABC_class'] = ABC['Cum_share'].apply(abc_analys)
ABC

           Revenue_stock         Piece  Cum_share ABC_class
StockCode
23843         168469.600  1.926707e-02   0.019267         A
22423         142264.750  1.627015e-02   0.035537         A
85123A        100547.450  1.149914e-02   0.047036         A
85099B         85040.540  9.725684e-03   0.056762         A
23166          81416.730  9.311246e-03   0.066073         A
...                  ...           ...        ...       ...
90084              0.850  9.721048e-08   1.000000         C
90104              0.850  9.721048e-08   1.000000         C
21268              0.840  9.606682e-08   1.000000         C
84227              0.420  4.803341e-08   1.000000         C
PADS               0.003  3.430958e-10   1.000000         C

[3661 rows x 4 columns]

In [49]:
ABC['ABC_class'].value_counts()

ABC_class
C    1958
B     920
A     783
Name: count, dtype: int64

In [50]:
data['data_mounth'] = data['InvoiceDate'].dt.to_period('M')
data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue,data_mounth
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30,2010-12
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010-12
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00,2010-12
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010-12
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010-12
...,...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France,10.20,2011-12
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France,12.60,2011-12
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60,2011-12
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60,2011-12
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France,14.85,2011-12

In [51]:
XYZ = data.groupby(['StockCode','data_mounth']).agg(
    Sales = ('Quantity', 'sum')
)
XYZ

                       Sales
StockCode data_mounth
10002     2010-12        224
          2011-01        337
          2011-02         50
          2011-03         23
          2011-04        189
...                      ...
C2        2011-11         22
          2011-12          3
PADS      2011-04          1
          2011-07          1
          2011-09          1

[30368 rows x 1 columns]

In [52]:
XYZ = XYZ.groupby('StockCode').agg(
    mean_sales = ('Sales','mean'),
    std_sales = ('Sales','std')
)
XYZ

           mean_sales   std_sales
StockCode
10002      164.600000  129.449990
10080       41.571429   32.413254
10120       19.200000   15.454593
10125      102.083333   60.941788
10133      237.300000  246.596859
...               ...         ...
90214W      12.000000         NaN
90214Y      30.500000   41.719300
90214Z      12.000000         NaN
C2          10.307692    5.588450
PADS         1.000000    0.000000

[3661 rows x 2 columns]

In [53]:
XYZ['cv'] = XYZ['std_sales']/XYZ['mean_sales']
XYZ

           mean_sales   std_sales        cv
StockCode
10002      164.600000  129.449990  0.786452
10080       41.571429   32.413254  0.779700
10120       19.200000   15.454593  0.804927
10125      102.083333   60.941788  0.596981
10133      237.300000  246.596859  1.039178
...               ...         ...       ...
90214W      12.000000         NaN       NaN
90214Y      30.500000   41.719300  1.367846
90214Z      12.000000         NaN       NaN
C2          10.307692    5.588450  0.542163
PADS         1.000000    0.000000  0.000000

[3661 rows x 3 columns]

In [54]:
def classification_xyz(xyz_class):
    if xyz_class < 0.5:
        return 'X'
    elif xyz_class >= 0.5 and xyz_class < 1:
        return 'Y'
    elif xyz_class == 'NaN':
        return 'Z'
    else:
        return 'Z'
XYZ['XYZ'] = XYZ['cv'].apply(classification_xyz)
XYZ

           mean_sales   std_sales        cv XYZ
StockCode
10002      164.600000  129.449990  0.786452   Y
10080       41.571429   32.413254  0.779700   Y
10120       19.200000   15.454593  0.804927   Y
10125      102.083333   60.941788  0.596981   Y
10133      237.300000  246.596859  1.039178   Z
...               ...         ...       ...  ..
90214W      12.000000         NaN       NaN   Z
90214Y      30.500000   41.719300  1.367846   Z
90214Z      12.000000         NaN       NaN   Z
C2          10.307692    5.588450  0.542163   Y
PADS         1.000000    0.000000  0.000000   X

[3661 rows x 4 columns]

In [55]:
XYZ.value_counts('XYZ')

XYZ
Y    1843
Z    1277
X     541
Name: count, dtype: int64

In [56]:
ABC = ABC.reset_index()
XYZ = XYZ.reset_index()
ABC

     StockCode  Revenue_stock         Piece  Cum_share ABC_class
0        23843     168469.600  1.926707e-02   0.019267         A
1        22423     142264.750  1.627015e-02   0.035537         A
2       85123A     100547.450  1.149914e-02   0.047036         A
3       85099B      85040.540  9.725684e-03   0.056762         A
4        23166      81416.730  9.311246e-03   0.066073         A
...        ...            ...           ...        ...       ...
3656     90084          0.850  9.721048e-08   1.000000         C
3657     90104          0.850  9.721048e-08   1.000000         C
3658     21268          0.840  9.606682e-08   1.000000         C
3659     84227          0.420  4.803341e-08   1.000000         C
3660      PADS          0.003  3.430958e-10   1.000000         C

[3661 rows x 5 columns]

In [57]:
matrix = ABC.merge(XYZ, on='StockCode')
matrix

,StockCode,Revenue_stock,Piece,Cum_share,ABC_class,mean_sales,std_sales,cv,XYZ
0,23843,168469.600,1.926707e-02,0.019267,A,80995.000000,NaN,NaN,Z
1,22423,142264.750,1.627015e-02,0.035537,A,951.846154,287.207198,0.301737,X
2,85123A,100547.450,1.149914e-02,0.047036,A,2827.923077,1387.364556,0.490595,X
3,85099B,85040.540,9.725684e-03,0.056762,A,3544.461538,1416.647252,0.399679,X
4,23166,81416.730,9.311246e-03,0.066073,A,8657.333333,24585.022000,2.839792,Z
...,...,...,...,...,...,...,...,...,...
3656,90084,0.850,9.721048e-08,1.000000,C,1.000000,NaN,NaN,Z
3657,90104,0.850,9.721048e-08,1.000000,C,1.000000,NaN,NaN,Z
3658,21268,0.840,9.606682e-08,1.000000,C,2.000000,NaN,NaN,Z
3659,84227,0.420,4.803341e-08,1.000000,C,1.000000,NaN,NaN,Z
3660,PADS,0.003,3.430958e-10,1.000000,C,1.000000,0.000000,0.000000,X

In [58]:
matrix['Grade'] = matrix['ABC_class'] + matrix['XYZ']
matrix

,StockCode,Revenue_stock,Piece,Cum_share,ABC_class,mean_sales,std_sales,cv,XYZ,Grade
0,23843,168469.600,1.926707e-02,0.019267,A,80995.000000,NaN,NaN,Z,AZ
1,22423,142264.750,1.627015e-02,0.035537,A,951.846154,287.207198,0.301737,X,AX
2,85123A,100547.450,1.149914e-02,0.047036,A,2827.923077,1387.364556,0.490595,X,AX
3,85099B,85040.540,9.725684e-03,0.056762,A,3544.461538,1416.647252,0.399679,X,AX
4,23166,81416.730,9.311246e-03,0.066073,A,8657.333333,24585.022000,2.839792,Z,AZ
...,...,...,...,...,...,...,...,...,...,...
3656,90084,0.850,9.721048e-08,1.000000,C,1.000000,NaN,NaN,Z,CZ
3657,90104,0.850,9.721048e-08,1.000000,C,1.000000,NaN,NaN,Z,CZ
3658,21268,0.840,9.606682e-08,1.000000,C,2.000000,NaN,NaN,Z,CZ
3659,84227,0.420,4.803341e-08,1.000000,C,1.000000,NaN,NaN,Z,CZ
3660,PADS,0.003,3.430958e-10,1.000000,C,1.000000,0.000000,0.000000,X,CX

In [59]:
matrix.value_counts('Grade')

Grade
CY    865
CZ    831
BY    530
AY    448
BZ    304
CX    262
AX    193
AZ    142
BX     86
Name: count, dtype: int64